Yan.MicroServices/Yan.MvcClient/Controllers/LifeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Yan.MvcClient.Clients;
using Yan.MvcClient.ViewModel;

namespace Yan.MvcClient.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    public class LifeController : Controller
    {
        /// <summary>
        /// 
        /// </summary>
        private readonly BillClient _client;

        /// <summary>
        /// 
        /// </summary>
        /// <param name="client"></param>
        public LifeController(BillClient client)
        {
            _client = client;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Index()
        {
            var model = await _client.GetCostStatics();
            var near = await _client.GetRecentExpenditure();
            LifeIndexViewModel vm = new LifeIndexViewModel
            {
                StatisticsOutput = model,
                NearCosts = near
            };
            return View(vm);
        }


        /// <summary>
        /// 年度饼图
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<List<EChartPieData>> GetYearPieData()
        {
            return await _client.GetYearPieData();
        }

        /// <summary>
        /// 月度饼图
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<List<EChartPieData>> GetMonthPieData()
        {
            return await _client.GetMonthPieData();
        }

        /// <summary>
        /// 账单列表
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> Bills(int index=1,int size=10)
        {
            var model = await _client.GetBillPage(new Models.BillPageInput
            {
                BeginTime = DateTime.Now.AddDays(-30),
                EndTime = DateTime.Now,
                Index = index,
                Size = size
            });

            return View();
        }

    }
}

Yan.MicroServices/Yan.MvcClient/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Yan.Core.Dtos;
using Yan.MvcClient.Clients;

namespace Yan.MvcClient.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    public class MessageController : Controller
    {
        /// <summary>
        /// 
        /// </summary>
        private readonly ArticleServiceClient _articleClient;

        /// <summary>
        /// 
        /// </summary>
        public MessageController(ArticleServiceClient articleClient)
        {
            _articleClient = articleClient;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="page"></param>
        /// <param name="size"></param>
        /// <returns></returns>
        public async Task<Clients.PageResultDto<MessageOutputDto>> GetMessagePage(int page, int size)
        {
            var result = await _articleClient.GetMessagePage(page, size);
            return result;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="skip"></param>
        /// <param name="size"></param>
        /// <returns></returns>
        public async Task<Clients.PageResultDto<MessageOutputDto>> GetMessageSkipPage(int skip, int size)
        {
            var result = await _articleClient.GetMessageSkipPage(skip, size);
            return result;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="message"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<MessageCreateDto> AddMessage(CreateMessagDto dto)
        {
            MessageCreateDto input = new MessageCreateDto() { Message = dto.Message, CreateTime = DateTime.Now };

            if (User.Identity.IsAuthenticated)
            {
                var nameClaim = User.Claims.FirstOrDefault(c => c.Type == "name");
                input.UserName = nameClaim == null ? "佚名" : nameClaim.Value;
            }
            else
            {
                input.UserName = "佚名";
            }
            var result = await _articleClient.AddMessage(input);
            if(result.State==1)
            {
                return input;
            }
            return null;
        }

    }
}

Yan.MicroServices/Yan.MvcClient/ViewComponents/DataCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Yan.MvcClient.Clients;
using Yan.MvcClient.ViewModel;

namespace Yan.MvcClient.ViewComponents
{
    /// <summary>
    /// 
    /// </summary>
    public class DataCountViewComponent:ViewComponent
    {
        /// <summary>
        /// 
        /// </summary>
        private readonly ArticleServiceClient _articleClient;

        /// <summary>
        /// 
        /// </summary>
        public DataCountViewComponent(ArticleServiceClient articleClient)
        {
            _articleClient = articleClient;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var articleCountModel = await _articleClient.GetArticleStaticCountByCategory();
            List<ArticleCountViewModel> articleCountViewModel = new List<ArticleCountViewModel>();
            foreach (var item in articleCountModel)
            {
                articleCountViewModel.Add(new ArticleCountViewModel()
                {
                    CategoryId = item.CategoryId,
                    CategoryName = item.CategoryName,
                    ArticleCount = item.ArticleCount
                });
            }
            return View("DataCount", articleCountViewModel);
        }
    }
}

Yan.MicroServices/Yan.MvcClient/Views/Shared/_ArticleInfoPartialView.cshtml
@using Yan.MvcClient.Clients;
@model ArticleListDto

<div style="margin-bottom:20px;padding-left:0px;">
    <div class="articleInfo-header">
        <h2><a asp-controller="Home" asp-action="Article" asp-route-id="@Model.Id">@Model.Title</a></h2>
        <div>
            <button type="button" class="btn btn-default btn-sm" style="border:0px;" >@Model.CategoryName</button>
            <span> 阅读：(@Model.ReadCount) · 点赞：(@Model.LikeCount）</span>
        </div>
        
    </div>
    <div class="articleInfo-content">
        <p>@Model.Remark</p>
    </div>
    <div>
        <a class="btn btn-danger" asp-controller="Home" asp-action="Article" asp-route-id="@Model.Id">阅读全文</a>
    </div>
</div>

<style>
    .articleInfo-header{
        margin-bottom:1em
    }
    .articleInfo-header h2 {
        font-size: 1.45em;
        line-height: 2em;
        border-bottom: 1px solid #ebebeb;
        margin-bottom: .5rem;
        font-family: inherit;
        font-weight: 500;
    }

    .articleInfo-header a:hover {
        cursor:pointer;
    }

    .articleInfo-content p {

        font-size: 1em;
        line-height: 1.8em;
        margin-top: 0;
        margin-bottom: 1rem;
        font-family: "微软雅黑","黑体","Consolas";
    }
</style>

Yan.MicroServices/Yan.MvcClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>YY · 爱编程</title>
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <style>
        .navbar-default li:hover,
        .navbar-default li:focus {
            color: #5e5e5e;
            background-color: beige;
        }
    </style>

</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top" style="background-color:ghostwhite;border-bottom:0px;" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a class="navbar-brand" href="/">
                    <img src="~/image/logo.png" style="margin-top:-5px;" />
                </a>
                <a class="navbar-brand" href="/" style="color:black">YY · 爱编程</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index"><span class="glyphicon glyphicon-home"></span> 主页 </a></li>
                    <li><a asp-controller="Message" asp-action="Index"><span class="glyphicon glyphicon-envelope"></span> 留言</a></li>
                    <li><a asp-controller="Life" asp-action="Index"><span class="glyphicon glyphicon-headphones"></span> 生活</a></li>
                </ul>
                <partial name="_Login.cshtml" />
            </div>
        </div>
    </nav>

    <div class="container" id="top">
        <div class="row" style="margin-top:60px">
            <div class="col-sm-3">
                <partial name="_RightMenu.cshtml" />
            </div>
            <div class="col-sm-9">
                @RenderBody()
            </div>
        </div>
    </div>

    <footer style="bottom:0px;width:100%;height:100px">
        <hr />
        <div class="container text-center">
            <p> © Copyright YY · 爱编程</p>
            <p style="color:#999999;">
                ASP.NET Core（3.1） on Linux
            </p>

        </div>
    </footer>


    <div class="go-to-top">
        <a href="#top"></a>
    </div>


    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <script>
        $(function () {
            $(window).scroll(function () {
                if ($(window).scrollTop() > 1000)
                    $('div.go-to-top').show();
                else
                    $('div.go-to-top').hide();
            });
        });
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Yan.MicroServices/Yan.MvcClient/Views/Shared/_Login.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
    <ul class="nav navbar-nav navbar-right">
        @if (!User.Identity.IsAuthenticated)
        {
            <li><a asp-controller="Home" asp-action="Login"><span class="glyphicon glyphicon-log-in"></span> 登录 </a></li>
        }
        else
        {
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                   aria-expanded="false">欢迎，@User.Claims.FirstOrDefault(c => c.Type == "name")?.Value <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="#">我的信息</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a asp-controller="Home" asp-action="Logout">登出</a></li>
                </ul>
            </li>
        }
    </ul>

Yan.MicroServices/Yan.MvcClient/Views/Shared/_RightMenu.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@


@using Yan.MvcClient.ViewModel;
@{ 
    var articleCount = ViewBag.ArticleCountByCategory as List<ArticleCountViewModel>;
}
<div class="about">
    <div class="about-header">
        <h3>关于本站</h3>
    </div>
    <div class="about-content">
        &nbsp;&nbsp;&nbsp;&nbsp;YY · 爱编程 专注.NetCore最佳实践。 本站是一个用于知识积累与分享的个人开源博客。主要技术栈为html、css、vue全家桶、axios、.NetCore。
        <hr style="margin-top:5px;margin-bottom:5px;">
        现在在北京工作。
        yanchuanpeng2008@163.com
    </div>
</div>

@await Component.InvokeAsync("DataCount")

<div class="weixin">
    <div class="weixin-header">
        <h3>微信</h3>
    </div>
    <div class="weixin-content">
        <img src="~/image/weixin.png"/>
    </div>
</div>

<div class="flink">
    <div class="flink-header">
        <h3>链接</h3>
    </div>
    <div class="count-content">
        <ul>
            <li><a href="http://82.156.187.171:9999" target="_blank">本站后台</a></li>
            <li><a href="http://82.156.187.171" target="_blank">本站Vue版本</a></li>
            <li><a href="https://www.baidu.com" target="_blank">百度</a></li>
        </ul>
    </div>
</div>

<style>

    .about, .weixin, .count, .flink {
        margin-left: -15px;
    }
    .about-header {
        text-align: center;
        font-size: 10px;
        padding: 10px;
        color: #DEDEDE;
        background: #8197fa;
        border-top-left-radius: 8px;
        border-top-right-radius: 8px;
    }
    .about-content {
        color: #1a1a1a;
        /*background: #F0FFFF;*/
        background: ghostwhite;
        padding: 10px;
        line-height: 28px;
        font-size: 14px;
        border-bottom-left-radius: 8px;
        border-bottom-right-radius: 8px;
    }
    .weixin-header, .flink-header {
        text-align: center;
        padding: 10px;
        color: #DEDEDE;
        background: #8197fa;
    }
    .weixin-content, .flink-content {
        color: #1a1a1a;
        /*background: #F0FFFF;*/
        background: ghostwhite;
        padding: 10px;
        display: flex;
        align-items: center;
        justify-content: center;
    }
        .weixin-content img {
            width: 150px;
            height: auto;
        }

    .about-header h3,
    .weixin-header h3,
    .count-header h3,
    .flink h3{
        margin-top: 0px;
        margin-bottom: 0px;
    }

    .count-header {
        text-align: center;
        padding: 15px;
        color: #DEDEDE;
        background: #8197fa;
    }
    .count-content {
        /*background: #F0FFFF;*/
        background: ghostwhite;
        line-height: 30px;
        font-size: 15px;
    }
        .count-content ul {
            display: block;
            width: 100%;
            margin-bottom: -10px;
        }
            .count-content ul li {
                list-style: none;
                width: 100%;
                padding: 5px 0;
                border-bottom: 1px dotted #d8e5f3;
            }
                .count-content ul li:hover {
                    background-color: lightgray;
                }
                .count-content ul li a {
                    font-size: 15px;
                    text-decoration: none;
                    color: #666;
                    cursor: pointer;
                    padding-left: 35px;
                }
                    .count-content ul li a:hover {
                        color: #000;
                    }


</style>