Yan.MicroServices/Yan.AdminUI2/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using Yan.AdminUI2.Models;

namespace Yan.AdminUI2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [Authorize]
        public IActionResult Index()
        {
            List<ElMenu> menus = new List<ElMenu>()
            {
                new ElMenu("看板","/home/dashboard","dashboard", "el-icon-menu","66","0" ),
                new ElMenu("导航一","path","name1", "el-icon-menu","1","0" ),
                new ElMenu("分组一","path","name2","el-icon-location","2","1"),
                new ElMenu("选项一","/home/index2","index2","el-icon-location","3","2"),
                new ElMenu("选项二","/home/index3","index3","el-icon-location","4","2"),
                new ElMenu("选项三","/home/index4","index4","el-icon-location","15","2"),
                new ElMenu("分组二","/path","name5","el-icon-location","5","1"),
                new ElMenu("分组三","path","name6","el-icon-location","6","1"),
                new ElMenu("选项一","/home/index2","name7","el-icon-location","7","6"),
                new ElMenu("选项二","/home/index2","name8","el-icon-location","8","6"),

                new ElMenu("系统管理","path","system", "el-icon-menu","9","0"),
                new ElMenu("角色管理","/Role/Index","role","el-icon-location","11","9"),
                new ElMenu("菜单管理","/System/Menu","menu","el-icon-location","12","9"),
                new ElMenu("用户管理","/System/User","user","el-icon-location","13","9"),

                new ElMenu("导航三","/path","name", "el-icon-menu","14","0")
            };
            return View(menus);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [Authorize]
        public IActionResult Index2()
        {
            var videos = new List<VideoViewModel>()
            {
                new VideoViewModel()
                {
                    Id = "10.100.32.131", Label = "10.100.32.131",
                    MainCodeStreamUrl = "http://10.100.32.140:8002/live?port=1935&app=videoapp&stream=streamch3_0",
                    SubCodeStreamUrl = "http://10.100.32.140:8002/live?port=1935&app=videoapp&stream=streamch3_1",
                    Children = new List<VideoViewModel>(),PlayState="123"
                },
                new VideoViewModel()
                {
                    Id = "10.100.32.132", Label = "10.100.32.132",
                    MainCodeStreamUrl = "http://10.100.32.140:8002/live?port=1935&app=videoapp&stream=streamch5_0",
                    SubCodeStreamUrl = "http://10.100.32.140:8002/live?port=1935&app=videoapp&stream=streamch5_1",
                    Children = new List<VideoViewModel>(),PlayState=""
                },
                new VideoViewModel()
                {
                    Id = "10.100.32.133", Label = "10.100.32.133",
                    MainCodeStreamUrl = "http://10.100.32.140:8002/live?port=1935&app=videoapp&stream=streamch6_0",
                    SubCodeStreamUrl = "http://10.100.32.140:8002/live?port=1935&app=videoapp&stream=streamch6_1",
                    Children = new List<VideoViewModel>(),PlayState=""
                },
                new VideoViewModel()
                {
                    Id = "10.100.32.134", Label = "10.100.32.134",
                    MainCodeStreamUrl = "http://10.100.32.140:8002/live?port=1935&app=videoapp&stream=streamch7_0",
                    SubCodeStreamUrl = "http://10.100.32.140:8002/live?port=1935&app=videoapp&stream=streamch7_1",
                    Children = new List<VideoViewModel>(),PlayState=""
                },
                new VideoViewModel()
                {
                    Id = "10.100.32.135", Label = "10.100.32.135",
                    MainCodeStreamUrl = "http://10.100.32.140:8002/live?port=1935&app=videoapp&stream=streamch14_0",
                    SubCodeStreamUrl = "http://10.100.32.140:8002/live?port=1935&app=videoapp&stream=streamch14_1",
                    Children = new List<VideoViewModel>(),PlayState=""
                },
                new VideoViewModel()
                {
                    Id = "10.100.32.136", Label = "10.100.32.136",
                    MainCodeStreamUrl = "http://10.100.32.140:8002/live?port=1935&app=videoapp&stream=streamch3_0",
                    SubCodeStreamUrl = "http://10.100.32.140:8002/live?port=1935&app=videoapp&stream=streamch3_0",
                    Children = new List<VideoViewModel>(),PlayState=""
                },
                new VideoViewModel()
                {
                    Id = "10.100.32.137", Label = "10.100.32.137",
                    MainCodeStreamUrl = "http://10.100.32.140:8002/live?port=1935&app=videoapp&stream=streamch3_0",
                    SubCodeStreamUrl = "http://10.100.32.140:8002/live?port=1935&app=videoapp&stream=streamch3_0",
                    Children = new List<VideoViewModel>(),PlayState=""
                },
                new VideoViewModel()
                {
                    Id = "10.100.32.138", Label = "10.100.32.138",
                    MainCodeStreamUrl = "http://10.100.32.140:8002/live?port=1935&app=videoapp&stream=streamch3_0",
                    SubCodeStreamUrl = "http://10.100.32.140:8002/live?port=1935&app=videoapp&stream=streamch3_0",
                    Children = new List<VideoViewModel>(),PlayState=""
                },
                new VideoViewModel()
                {
                    Id = "10.100.32.139", Label = "10.100.32.139",
                    MainCodeStreamUrl = "http://10.100.32.140:8002/live?port=1935&app=videoapp&stream=streamch3_0",
                    SubCodeStreamUrl = "http://10.100.32.140:8002/live?port=1935&app=videoapp&stream=streamch3_0",
                    Children = new List<VideoViewModel>(),PlayState=""
                }

            };

            var js = JsonConvert.SerializeObject(videos);

            ViewBag.Data = videos;
            return View();
        }

        [Authorize]
        public IActionResult Index3()
        {
            return View();
        }


        [Authorize]
        public IActionResult Index4()
        {
            return View();
        }

        [Authorize]
        public IActionResult DashBoard()
        {
            return View();
        }

        [Authorize]
        public IActionResult GetArticleLst(int page,int limit)
        {
            var lst = new List<ArticleViewModel>
            {
                new ArticleViewModel(){Id="1",Title = "C#",Remark =page.ToString()+" "+ limit.ToString()},
                new ArticleViewModel(){Id="2",Title = "Java",Remark = page.ToString()+" "+limit.ToString()},
                new ArticleViewModel(){Id="3",Title = "C++",Remark =page.ToString()+" "+ limit.ToString()},
                new ArticleViewModel(){Id="4",Title = "C",Remark = page.ToString()+" "+limit.ToString()},
            };

            Paged<ArticleViewModel> result = new Paged<ArticleViewModel>()
            {
                TotalCount = 110,
                Datas = lst
            };


            return Json(result);
        }
    }
}

Yan.MicroServices/Yan.AdminUI2/ViewComponents/LeftMenuViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Yan.AdminUI2.Models;

namespace Yan.AdminUI2.ViewComponents
{
    [ViewComponent(Name = "LeftMenu")]
    public class LeftMenuViewComponent:ViewComponent
    {
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public async Task<IViewComponentResult> InvokeAsync(List<ElMenu> menus)
        {
            return View(menus);
        }
    }
}

Yan.MicroServices/Yan.AdminUI2/ViewComponents/PageTableViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Yan.AdminUI2.Models;

namespace Yan.AdminUI2.ViewComponents
{
    /// <summary>
    /// page table view component
    /// </summary>
    [ViewComponent(Name = "PageTable")]
    public class PageTableViewComponent:ViewComponent
    {
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = new ArticleViewModel
            {
                Id = "1", Title = "2", Remark = "3"
            };

            return View(model);
        }
    }



}

Yan.MicroServices/Yan.AdminUI2/Views/Home/DashBoard.cshtml
@{
    Layout = null;
}

<template id="dashboard">
    <div  style="height: 100%; border: 0px;">
        <h1>dashboard123</h1>
    </div>
</template>

<script type="text/javascript">
    //Vue.component("dashboard",
    //    {
    //        template: "#dashboard",
    //        created() {
    //            console.log('dashboard created');
    //        }
    //    });

    var dashboard = {
        name: 'dashboard',
        template: '#dashboard',
        created: function() {
            console.log('dashboard created');
        }
    };
</script>

Yan.MicroServices/Yan.AdminUI2/Views/Home/Index.cshtml
@using System.Linq
@using Microsoft.CodeAnalysis
@model List<ElMenu>
@{
    ViewData["Title"] = "YY后台管理系统";
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/home.css" />
    <link rel="stylesheet" href="~/css/font-awesome.css" />
    <link rel="stylesheet" href="~/lib/element-ui/theme-chalk/index.css" />
    <link rel="stylesheet" href="~/font/iconfont.css" />
    <link rel="stylesheet" href="~/css/element.css"/>
</head>
<body>
    <div id="app">
        <el-container>
            <el-header>
                <div class="home-logo">
                    <img src="~/image/logo1.png">
                    <span>@ViewData["Title"]</span>
                </div>

                <div class="home-toggle">
                    <span @@click="isCollapse=!isCollapse">
                        <i class="el-icon-menu"></i>
                    </span>
                </div>

                <div class="home-right">
                    <a href="javascript:;" title="全屏" style="padding-right: 10px;" @@click="fullScreen">
                        <i class="fa fa-arrows-alt fa-lg" ref="fullScreenIcon" style="color: white"></i>
                    </a>
                    <el-dropdown menu-align="start">
                        <div class="user-container">
                            <img src="~/image/user.jpg">
                            <span>
                                @if (User.Identity.IsAuthenticated)
                                {
                                    @User.Identity.Name
                                }
                            </span>
                        </div>
                        <el-dropdown-menu slot="dropdown">
                            <el-dropdown-item divided>
                                <a style="text-decoration: none" asp-action="LogOut" asp-controller="Login"><span>登&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;出</span></a>
                            </el-dropdown-item>
                        </el-dropdown-menu>
                    </el-dropdown>
                </div>
            </el-header>

            <el-container>
                <el-aside :width="isCollapse? '70px':'250px'">
                    @await Component.InvokeAsync("LeftMenu", new { menus = Model })
                </el-aside>
                <el-main style="padding: 0">
                    <el-tabs v-model="tabsIndex" type="border-card" @@tab-remove="removeTab" @@tab-click="clickTab" style="border: 1px solid #304156;">
                        <el-tab-pane v-for="(item,index) in tabsData" :key="item.name" :label="item.title" :name="item.name" :closable="item.closeable">
                            <transition-group name="form-fade" mode="in-out">
                                <div :id="'tab_'+item.name" v-bind:key="'tab_'+item.name"></div>
                                <component :is="item.content" :ref="item.name" :tabIndex="item.name" v-bind:key="item.name"/>
                            </transition-group>
                        </el-tab-pane>
                    </el-tabs>
                </el-main>
            </el-container>

        </el-container>
    </div>

</body>
</html>

@*<partial name="DashBoard"/>*@

<script type="text/javascript" src="~/lib/jquery/dist/jquery.js"></script>
<script type="text/javascript" src="~/lib/axios/axios.js"></script>
<script type="text/javascript" src="~/lib/vue/vue.js"></script>
<script type="text/javascript" src="~/lib/element-ui/index.js"></script>
<script type="text/javascript" src="~/lib/screenfull/screenfull.js"></script>
<script type="text/javascript" src="~/js/admin.js"></script>
<script>
    var app = new Vue({
        el: '#app',
        data: {
            isCollapse: false,
            isFullscreen: false,
            tabsData: [
                //{
                //    title: 'DashBoard',
                //    name: 'DashBoard',
                //    content: dashboard,
                //    closeable: false
                //}
            ],
            tabsIndex: 'dashboard',
            defaultActive: 'dashboard'
        },
        created(){
            this.addTab("看板", "/Home/DashBoard", "dashboard", false);
        },
        methods: {
            fullScreen() {
                window.screenfull.toggle();
                this.isFullscreen = !this.isFullscreen;
                var c = 'fa-compress';
                var f = 'fa-arrows-alt';
                var i = this.$refs.fullScreenIcon;
                if (this.isFullscreen) {
                    if (i.classList.contains(f)) {
                        i.classList.add(c);
                        i.classList.remove(f);
                    }
                } else {
                    i.classList.add(f);
                    i.classList.remove(c);
                }
            },
            addTab(title, path, name, closeable = true) {
                let tabs = this.tabsData;
                let self = this;
                for (let tab of tabs) {
                    if (tab.name === name) {
                        this.tabsIndex = name;
                        return false;
                    }
                }
                this.tabsData.push({
                    title: title,
                    name: name,
                    content: null,
                    closeable: closeable
                });
                this.tabsIndex = name;
                $.ajax({
                    url: path,
                    headers: {
                        axios: "true"
                    },
                    success: function (result) {
                        $("#tab_" + name).html(result);
                        self.tabsData[self.tabsData.length - 1].content = eval(name);
                    },
                    error: function (error) {
                        console.log(error);
                        switch (error.status) {
                            case 401:
                                self.$confirm('登录已超时，请重新登录','提示',
                                    {
                                        confirmButtonText: '重新登录',
                                        cancelButtonText: '取消',
                                        type: 'warning'
                                    }).then(() => {
                                    window.location.href = "/Login";
                                });
                            case 404:
                            case 500:
                                $("#tab_" + name).html('<h1>未找到页面,请联系管理员</h1>');
                                self.tabsData[self.tabsData.length - 1].content = eval(name);
                        }
                    }
                });

                return true;
            },
            removeTab(targetName) {
                let tabs = this.tabsData;
                let activeName = this.tabsIndex;
                if (activeName === targetName) {
                    tabs.forEach((tab, index) => {
                        if (tab.name === targetName) {
                            var nextTab = tabs[index + 1] || tabs[index - 1];
                            if (nextTab) {
                                activeName = nextTab.name;
                            }
                        }
                    });
                }

                this.tabsIndex = activeName;
                this.tabsData = tabs.filter(tab => tab.name !== targetName);
                this.defaultActive = activeName;
            },
            clickTab(tab) {
                var name = tab.name;
                this.defaultActive = name;
            }
        }
    });
</script>

Yan.MicroServices/Yan.AdminUI2/Views/Home/Index3.cshtml
@{
    Layout = null;
}


<template id="index3">
    <div style="background: aquamarine;">
        <el-table :data="article" style="width: 100%">
            <el-table-column prop="id"
                             label="id"
                             width="180">
            </el-table-column>
            <el-table-column prop="title"
                             label="名称"
                             width="180">
            </el-table-column>
            <el-table-column prop="remark"
                             label="简介">
            </el-table-column>
        </el-table>
        <el-pagination @@size-change="handleSizeChanged" @@current-change="handleCurrentPageChanged" :current-page="currentPage"
                       :page-sizes="pageSize" :page-size="limit" layout="total, -> ,sizes, -> , prev, pager, next" :total="count">
        </el-pagination>
    </div>
</template>

<script type="text/javascript">
    var index3 = {
        template: "#index3",
        data: function(){
            return {
                article: [],
                pageSize: [5, 10, 20, 50, 100],
                limit: 20,
                currentPage: 1,
                count:0
            }
        },
        mounted: function () {
            this.getData();
        },
        methods: {
            async getData() {
                let here = this;
                var data = await httpRequestService.GET('/Home/GetArticleLst?page=' +
                    this.currentPage +
                    '&limit=' +
                    this.limit);

                here.count = data.totalCount;
                here.article = data.datas;
            },
            handleSizeChanged (val) {
                this.limit = val;
                this.currentPage = 1;
                this.getData();
            },
            handleCurrentPageChanged (val) {
                this.currentPage = val;
                this.getData();
            }
        }

    }
</script>

Yan.MicroServices/Yan.AdminUI2/Views/Home/Index4.cshtml
@{
    Layout = null;
}

<template id="index4">
    @await Component.InvokeAsync("PageTable")
</template>

<script type="text/javascript">
    var index4 = {
        template: "#index4"
    }
</script>